# Generated by Django 4.0.3 on 2022-04-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movei',
            name='date',
        ),
    ]
